version: 2.1

jobs:
  build:
    macos:
      xcode: 11.2.1
    steps:
      - run: cat ~/.circle_image
      - run: xcodebuild -version
      - checkout
      - run: ruby -v
      - run: mdutil -a -s
      - run: uname -a
