version: 2
jobs:
  build:
    macos:
      xcode: "10.1.0"
    shell: /bin/bash --login -eo pipefail
    steps:
      - run:
          name: Set Ruby Version
          command: echo "ruby-2.6.1" > ~/.ruby-version
      - run: ruby -v
