version: 2.1

jobs:

  build:
    docker:
      - image: cimg/base:2020.05
    steps:
      - run: echo build

  test:
    docker:
      - image: cimg/base:2020.05
    steps:
      - run: echo test

  deploy:
    docker:
      - image: cimg/base:2020.05
    steps:
      - run: echo deploy

workflows:
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
