version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.05
    steps:
      - run:
          command: |
            echo << pipeline.id                 >>
            echo << pipeline.number             >>
            echo << pipeline.project.git_url    >>
            echo << pipeline.project.type       >>
            echo << pipeline.git.tag            >>
            echo << pipeline.git.branch         >>
            echo << pipeline.git.revision       >>
            echo << pipeline.git.base_revision  >>
