version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01 # Ubuntu 16.04, docker 18.09.3, docker-compose 1.23.1
    steps:
      - run: uname
      - run: curl "https://zlib.net/zlib-1.2.11.tar.gz" > /dev/null
      - run: traceroute zlib.net
