version: 2.1

jobs:
  build:
    macos:
      xcode: 11.3.1
    steps:
      - run: git clone git@github.com:git/git.git
      - run: brew unlink gettext && brew link gettext --force
      - run:
          command: time make
          working_directory: ~/project/git
