version: 2.1


jobs:
  build:
    parameters:
      xcode:
         type: string
    macos:
      xcode: << parameters.xcode >>
    steps:
      - run: xcrun simctl list &>/dev/null

workflows:
  workflow:
    jobs:
      - build: {xcode: 10.1.0}
      - build: {xcode: 10.0.0}
      - build: {xcode: 9.4.1}
      - build: {xcode: 9.4.0}
      - build: {xcode: 9.3.1}
      - build: {xcode: 9.3.0}
      - build: {xcode: 9.2.0}
      - build: {xcode: 9.1.0}
      - build: {xcode: 9.0.1}
      - build: {xcode: 8.3.3}
