version: 2.1
orbs:
  continuation: circleci/continuation@0.2.0
setup: true

jobs:
  build:
    docker:
      - image: mikefarah/yq:4.11.2
    steps:
      - checkout
      - run:
          name: Convert Config
          command:  eval -P .circleci/config.json > continue.yml
      - continuation/continue:
          configuration_path: continue.yml
