version: 2.1

jobs:

  build:
    docker:
      - image: cimg/base:2020.05
    steps:
      - run: echo build

  test:
    docker:
      - image: cimg/base:2020.05
    steps:
      - run: echo test
      - run: |
          curl -X POST -H "Webhook-Workflow-Id: $CIRCLE_WORKFLOW_ID" "https://0c3c11df2ae2.ngrok.io/circleci/fake-webhook"

  deploy:
    docker:
      - image: cimg/base:2020.05
    steps:
      - run: echo deploy

workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - approval:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - approval


notify:
  webhooks:
    - url: https://0c3c11df2ae2.ngrok.io/circleci/webhook
