version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout

# doubting, bleak ever repeating said dreaming as faintly distinctly door.
# surcease wrought muttered, at my doubting, visiter and entrance said chamber my

other_data:
  - doubting, bleak ever repeating said dreaming as faintly distinctly door.
  - surcease wrought muttered, at my doubting, visiter and entrance said chamber my
