version: 2.1
jobs:
  build:
    macos:
      xcode: 10.2.1
    steps:
      - checkout
      - run:
          environment:
            HOMEBREW_NO_AUTO_UPDATE: "1"
          command: brew install wget
      - run: wget "https://circleci.com"
