version: 2.1

orbs:
  marc:
    commands:
      yell:
        steps:
          - echo "HALLO POOH"

jobs:
  build:
    docker:
      - image: buildpack-deps:16.04-curl
    steps:
      - run: env
      - run: sleep 3
