# A config with no workflow defined.
# Just a single job.
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3
    steps:
      - checkout
workflows:
  version: 2
  commit:
    jobs:
      - build
