version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.05
    steps:
      - run: mkfifo wait-for-this
      - run:
          name: Slow Background Task
          background: true
          command: |
            sleep 10
            echo 'done' > wait-for-this
      - run:
          name: Fast Foreground Task
          command: ls -la
      - run:
           name: Wait for background task
           command: cat < wait-for-this
