version: 2.1

jobs:

  build:
    docker:
      - image: cimg/base:2020.05
    steps:
      - run: echo build

  test:
    docker:
      - image: cimg/base:2020.05
    steps:
      - checkout
      - run: echo test
      - run: ./fake_webhook.sh

  deploy:
    docker:
      - image: cimg/base:2020.05
    steps:
      - run: echo deploy

workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - approval:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - approval

notify:
  webhooks:
    - url: https://ecosystem.eu.ngrok.io/circleci/webhook
