version: 2.1

jobs:
  windows:
    shell: powershell.exe
    resource_class: windows.medium
    machine:
      image: windows-server-2019-poc
    steps:
      - run: echo Hello, CircleCI

  machine:
    machine: true
    steps:
      - checkout
      - run: echo Hello, CircleCI

  docker:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: echo Hello, CircleCI

workflows:
  workflow:
    jobs:
      - docker
      - machine
      - windows
