version: 2.1

jobs:
  build:
    macos:
      xcode: 11.0.0
    steps:
      - run: echo $PATH
      - run: which ruby
      - run: ruby -v
      - run: echo "ruby-2.6" > ~/.ruby-version
      - run: which ruby
      - run: ruby -v
