version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.05
    steps:
      - run:
          name: Sleep
          command: sleep 15
      - run:
          name: Sleep
          command: sleep 15
      - run:
          name: Sleep
          command: sleep 15
      - run:
          name: Sleep
          command: sleep 15
      - run:
          name: Sleep
          command: sleep 15
      - run:
          name: Sleep
          command: sleep 15
      - run:
          name: Sleep
          command: sleep 15
      - run:
          name: Sleep
          command: sleep 15
