version: 2.1

workflows:
  big_workflow:
    jobs:
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job
    - big_job

commands:
  big_step:
    steps:
      - big_command
      - big_command
      - big_command
  big_command:
    steps:
      - run:
          name: a big bunch o stuff
          command: |
            echo "

            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra justo. Dolor morbi non arcu risus quis varius. Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis gravida. Consequat mauris nunc congue nisi vitae. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Tristique risus nec feugiat in fermentum posuere urna nec. Dignissim enim sit amet venenatis. Eu ultrices vitae auctor eu augue ut lectus. Aliquam etiam erat velit scelerisque in. Dui sapien eget mi proin sed libero enim.

            Eleifend donec pretium vulputate sapien. Enim diam vulputate ut pharetra sit amet aliquam. Vitae aliquet nec ullamcorper sit amet risus. Id donec ultrices tincidunt arcu non sodales. Suspendisse in est ante in nibh mauris cursus mattis molestie. Ut pharetra sit amet aliquam. Elit at imperdiet dui accumsan sit amet. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget. Odio facilisis mauris sit amet massa. Lobortis feugiat vivamus at augue eget arcu dictum varius. Viverra mauris in aliquam sem fringilla ut morbi tincidunt. Nisl tincidunt eget nullam non. Purus non enim praesent elementum facilisis leo vel fringilla est. Integer vitae justo eget magna fermentum. Ipsum faucibus vitae aliquet nec ullamcorper sit amet.

            Venenatis tellus in metus vulputate eu scelerisque felis imperdiet. Amet mattis vulputate enim nulla aliquet porttitor lacus. Faucibus turpis in eu mi bibendum neque. Sem et tortor consequat id porta. Neque egestas congue quisque egestas. Neque laoreet suspendisse interdum consectetur libero id faucibus nisl. Arcu cursus vitae congue mauris. Amet massa vitae tortor condimentum lacinia quis vel eros donec. Arcu odio ut sem nulla pharetra. Sodales ut etiam sit amet nisl purus in mollis nunc. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Eu tincidunt tortor aliquam nulla facilisi cras fermentum odio eu. Gravida arcu ac tortor dignissim convallis aenean et tortor at. Varius morbi enim nunc faucibus a pellentesque. Diam vel quam elementum pulvinar etiam non. Et netus et malesuada fames ac turpis egestas. Enim sit amet venenatis urna cursus eget nunc. Cras pulvinar mattis nunc sed blandit libero volutpat sed. Id nibh tortor id aliquet lectus proin nibh nisl.

            Viverra aliquet eget sit amet tellus cras. Velit dignissim sodales ut eu sem integer vitae. Amet volutpat consequat mauris nunc congue nisi vitae. Fermentum et sollicitudin ac orci phasellus. Mattis rhoncus urna neque viverra. Aliquam sem et tortor consequat id porta nibh. Suspendisse faucibus interdum posuere lorem ipsum. Senectus et netus et malesuada fames ac turpis egestas maecenas. Lectus arcu bibendum at varius. Et malesuada fames ac turpis egestas maecenas pharetra convallis. Arcu bibendum at varius vel pharetra vel turpis nunc. Hendrerit gravida rutrum quisque non. Augue neque gravida in fermentum et sollicitudin ac orci. Non enim praesent elementum facilisis leo. Ac orci phasellus egestas tellus. Sit amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar.

            Et tortor consequat id porta nibh venenatis cras sed felis. Feugiat nisl pretium fusce id velit ut tortor pretium viverra. Diam ut venenatis tellus in metus. Pretium lectus quam id leo in vitae turpis. Magna fermentum iaculis eu non diam phasellus vestibulum lorem sed. Aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Amet commodo nulla facilisi nullam vehicula ipsum a. At tempor commodo ullamcorper a lacus. Sed sed risus pretium quam vulputate dignissim suspendisse. Integer eget aliquet nibh praesent tristique magna sit. Non blandit massa enim nec dui nunc. Metus dictum at tempor commodo ullamcorper a lacus. Neque viverra justo nec ultrices. Habitant morbi tristique senectus et netus et malesuada.

            "

jobs:
  big_job:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
      - big_step
